export const classic = [
  "wands-queen",
  "cups-2",
  "cups-3",
  "cups-4",
  "cups-5",
  "cups-6",
  "cups-7",
  "cups-8",
  "cups-9",
  "cups-10",
  "cups-ace",
  "cups-king",
  "cups-knight",
  "cups-page",
  "cups-queen",
  "ma-death",
  "ma-judgement",
  "ma-justice",
  "ma-strength",
  "ma-temperance",
  "ma-the-chariot",
  "ma-the-devil",
  "ma-the-emperor",
  "ma-the-empress",
  "ma-the-fool",
  "ma-the-hanged-man",
  "ma-the-hermit",
  "ma-the-hierophant",
  "ma-the-high-priestess",
  "ma-the-lovers",
  "ma-the-magician",
  "ma-the-moon",
  "ma-the-star",
  "ma-the-sun",
  "ma-the-tower",
  "ma-the-world",
  "ma-wheel-of-fortune",
  "pentacles-2",
  "pentacles-3",
  "pentacles-4",
  "pentacles-5",
  "pentacles-6",
  "pentacles-7",
  "pentacles-8",
  "pentacles-9",
  "pentacles-10",
  "pentacles-ace",
  "pentacles-king",
  "pentacles-knight",
  "pentacles-page",
  "pentacles-queen",
  "swords-2",
  "swords-3",
  "swords-4",
  "swords-5",
  "swords-6",
  "swords-7",
  "swords-8",
  "swords-9",
  "swords-10",
  "swords-ace",
  "swords-king",
  "swords-knight",
  "swords-page",
  "swords-queen",
  "wands-2",
  "wands-3",
  "wands-4",
  "wands-5",
  "wands-6",
  "wands-7",
  "wands-8",
  "wands-9",
  "wands-10",
  "wands-ace",
  "wands-king",
  "wands-knight",
  "wands-page",
];

export const crypto = [
  "0 The hierophant",
  "1 The Magician",
  "2 The Hight Priestess",
  "3 The The Empress",
  "4 The Emperor",
  "5 The hierophant",
  "6 The lovers",
  "7 The chariot",
  "8 strenght",
  "9 the hermit",
  "10 wheel fortune",
  "11 justice",
  "12 the hanged man",
  "13 death",
  "14 temperance",
  "15 the devil",
  "16 the tower",
  "17 the star",
  "18 the moon",
  "19 the sun",
  "20 judgement",
  "21 the world",
  "Ace of Cups",
  "Ace of Pentacles",
  "Ace of Swords",
  "Ace of Wands",
  "Eight of Cups",
  "Eight of Pentacles",
  "Eight of Swords",
  "Eight of Wands",
  "Five of Cups",
  "Five of Pentacles",
  "Five of Swords",
  "Five of Wands",
  "Four of Cups",
  "Four of Pentacles",
  "Four of Swords",
  "Four of Wands",
  "King of Cups",
  "King of Pentacles",
  "King of Swords",
  "King of Wands",
  "Knight of Cups",
  "Knight of Pentacles",
  "Knight of Swords",
  "Knight of Wands",
  "Nine of Cups",
  "Nine of Pentacles",
  "Nine of Swords",
  "Nine of Wands",
  "Page of Cups",
  "Page of Pentacles",
  "Page of Swords",
  "Queen of Cups",
  "Queen of Pentacles",
  "Queen of Swords",
  "Queen of Wands",
  "Seven of Cups",
  "Seven of Pentacles",
  "Seven of Swords",
  "Seven of Wands",
  "Six of Cups",
  "Six of Pentacles",
  "Six of Swords",
  "Six of Wands",
  "Ten of Cups",
  "Ten of Pentacle",
  "Ten of Swords",
  "Ten of Wands",
  "The Emperor 4",
  "Three of Cups",
  "Three of Pentacles",
  "Three of Swords",
  "Three of Wands",
  "Two of Cups",
  "Two of Pentacles",
  "Two of Swords",
  "Two of Wands",
];
